[package]
name = "cache"
version = "0.1.0"
authors = ["ndenoyelle <ndenoyelle@anl.gov>"]
edition = "2018"

[dependencies]
tempfile = { version = "3.2.0", optional = true }
serde = { version = "1.0.125", optional = true }
bincode = { version = "1.3.3", optional = true }

[dev-dependencies]
rand = "0.8.3"

[features]
default = [ "stream" ]
stream = [ "serde", "bincode", "tempfile" ]
