[package]
name = "cache"
version = "0.1.0"
authors = ["ndenoyelle <ndenoyelle@anl.gov>"]
edition = "2021"

[dependencies]
tempfile = { version = "3.2.0", optional = true }
serde = { version = "1.0.125", optional = true }
bincode = { version = "1.3.3", optional = true }

[dev-dependencies]
rand = "0.8.3"

[features]
default = []
# Feature enabling building implementation into a stream of bytes.
# Converting structure to bytes requires to be able to serialize and
# deserialize from the stream (serde + bincode).
# Additionally, tempfile is used to generate the files where the key/value
# are stored.
stream = [ "serde", "bincode", "tempfile" ]
